import React, { useState, useEffect } from 'react';
import { toast } from 'react-toastify';
import '../styles/pages.css';

const ReportsPage = ({ villages }) => {
  const [reports, setReports] = useState([]);

  useEffect(() => {
    const lastReport = localStorage.getItem('lastReport');
    if (lastReport) {
      const report = JSON.parse(lastReport);
      setReports([{
        id: 1,
        village: report.village,
        date: new Date(report.date).toLocaleDateString(),
        type: 'Comprehensive Analysis',
        status: 'Ready for Download'
      }]);
    }
  }, []);

  const handleDownload = (report) => {
    const content = `
GRAM URJA - RENEWABLE ENERGY ASSESSMENT REPORT
================================================

Village: ${report.village}
Date: ${report.date}
Report Type: ${report.type}

ENERGY ASSESSMENT SUMMARY
==========================

Solar Energy: 85/100 (EXCELLENT)
- High solar irradiance potential
- Recommended for solar PV installation
- Estimated ROI: 5-7 years

Wind Energy: 45/100 (MODERATE)
- Moderate wind resources
- Small turbines feasible
- Requires detailed site assessment

Biomass Energy: 62/100 (MODERATE)
- Good agricultural waste availability
- Biogas plant recommended
- Excellent circular economy benefits

Hydro Energy: 35/100 (LOW)
- Limited hydroelectric potential
- Micro-hydro only if water resources available

RECOMMENDATIONS
===============
1. Priority: Install solar panels first
2. Secondary: Setup biogas facility
3. Tertiary: Consider small wind turbines
4. Future: Explore hydro options

FINANCIAL SUMMARY
=================
Estimated Initial Investment: ₹50-70 Lakhs
Annual Cost Savings: ₹15-20 Lakhs
Payback Period: 5-7 years
Government Subsidies: Available

For more information, visit: gram-urja.com

Generated by GRAM URJA Platform
    `;

    const element = document.createElement('a');
    element.setAttribute('href', 'data:text/plain;charset=utf-8,' + encodeURIComponent(content));
    element.setAttribute('download', `${report.village}_report_${report.date}.txt`);
    element.style.display = 'none';
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);

    toast.success('Report downloaded successfully!');
  };

  return (
    <div className="reports-container">
      <div className="reports-header">
        <h2>Energy Analysis Reports</h2>
        <p className="subtitle">{reports.length} reports generated</p>
      </div>

      {reports.length > 0 ? (
        <div className="reports-grid">
          {reports.map((report) => (
            <div key={report.id} className="report-card">
              <div className="report-header">
                <h3>{report.village}</h3>
                <span className="status ready">{report.status}</span>
              </div>
              <div className="report-info">
                <p><strong>📅 Date:</strong> {report.date}</p>
                <p><strong>📋 Type:</strong> {report.type}</p>
              </div>
              <button className="btn-download" onClick={() => handleDownload(report)}>
                📥 Download Report
              </button>
            </div>
          ))}
        </div>
      ) : (
        <div className="no-reports">
          <p className="empty-icon">📄</p>
          <p>No reports yet. Run analysis on a village to generate reports.</p>
        </div>
      )}
    </div>
  );
};

export default ReportsPage;
